version: '3'

# do not use it for production

services:
  postgres:
    image: postgres:10
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - beitris
    ports:
      - 5439:5432
    environment:
      - POSTGRES_DB=beitris
      - POSTGRES_USER=beitris
      - POSTGRES_PASSWORD=beitris

  backend:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    networks:
      - beitris

  daphne:
    build: .
    command: bash -c "daphne -b 0.0.0.0 -p 8001 beitris.asgi:application"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    ports:
    - 8001:8001
    networks:
      - beitris

  redis:
    image: redis
    networks:
      - beitris

  celery:
    build: .
    command: ["celery", "worker", "--app=beitris.celery.app", "--concurrency=1", "--hostname=worker@%h", "--loglevel=INFO"]
    volumes:
      - .:/app
    networks:
      - beitris
    depends_on:
      - redis

  frontend:
    build: ./frontend
    command: bash -c 'yarn install && yarn start'
    stdin_open: true
    environment:
      - NODE_ENV=dev
    depends_on:
      - backend
    networks:
      - beitris
    volumes:
      - ./frontend:/app

  nginx:
    build:
      context: .
      dockerfile: nginx.dev.Dockerfile
    depends_on:
      - backend
      - frontend
    volumes:
      - ./media/:/app/media
      - ./static/:/app/static
      - /opt/letsencrypt/:/var/www/letsencrypt/
      - /etc/letsencrypt/:/etc/letsencrypt/
    links:
      - frontend
      - backend
    ports:
      - 80:80
    networks:
      - beitris

volumes:
  postgres_data:

networks:
  beitris:
    driver: bridge
