# Generated by Django 3.0.3 on 2020-03-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='query',
            field=models.TextField(blank=True, help_text='https://query.wikidata.org/', null=True),
        ),
    ]
