# Generated by Django 3.0.3 on 2020-02-26 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('language', models.CharField(default='en', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='FactoryFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.CharField(max_length=35)),
                ('entity', models.CharField(max_length=35)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Factory')),
            ],
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.CharField(max_length=35)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Factory')),
            ],
        ),
    ]
