# Generated by Django 3.0.3 on 2020-04-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200314_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_channel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
