# Generated by Django 3.0.3 on 2020-03-14 10:55

import common.enums
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wikidata_parent_entity', models.CharField(blank=True, max_length=35, null=True)),
                ('name', models.CharField(max_length=35)),
                ('enabled', models.BooleanField(default=False)),
                ('language', models.CharField(default='en', max_length=3)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('wikidata_id', models.CharField(max_length=35)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Category')),
            ],
            options={
                'unique_together': {('category', 'name'), ('category', 'wikidata_id')},
            },
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('question_wikidata_prop', models.CharField(max_length=35)),
                ('type', models.CharField(choices=[(common.enums.QuestionTypes['image'], 'image'), (common.enums.QuestionTypes['text'], 'text'), (common.enums.QuestionTypes['sounds'], 'sounds'), (common.enums.QuestionTypes['coords'], 'coords')], max_length=10)),
                ('is_question_in_child', models.BooleanField(default=False)),
                ('child_prop', models.CharField(blank=True, max_length=35, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Category')),
            ],
            options={
                'verbose_name_plural': 'Question Types',
            },
        ),
        migrations.CreateModel(
            name='ObjectAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='quiz.Object')),
            ],
            options={
                'verbose_name_plural': 'Object Aliases',
            },
        ),
    ]
