# Generated by Django 3.0.3 on 2020-03-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontype',
            name='type',
            field=models.CharField(choices=[('image', 'image'), ('text', 'text'), ('sounds', 'sounds'), ('coords', 'coords')], max_length=10),
        ),
    ]
