# Generated by Django 3.0.3 on 2020-02-28 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0002_category_enabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='objectalias',
            options={'verbose_name_plural': 'Object Aliases'},
        ),
        migrations.AlterModelOptions(
            name='questiontype',
            options={'verbose_name_plural': 'Question Types'},
        ),
        migrations.AddField(
            model_name='answer',
            name='right',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='question_wikidata_prop',
            field=models.CharField(default='P18', max_length=35),
            preserve_default=False,
        ),
    ]
