# Generated by Django 3.0.3 on 2020-03-15 17:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0002_auto_20200314_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='skip_request',
            field=models.ManyToManyField(related_name='skip_question', to=settings.AUTH_USER_MODEL),
        ),
    ]
