# Generated by Django 3.0.3 on 2020-05-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_question_skip_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer',
            field=models.CharField(default='undefined', max_length=255),
            preserve_default=False,
        ),
    ]
